### ISSUE TITLE
Добавить .github/ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by Spalishe** [UnitLabs/issues#3]
Мне одному кажется, то что среди этих проблем на гитхабе появится что то в духе: "ыыыыыы чего то нету что то сломано идите чините как это решить я хз делайте.". И чтобы хоть как то убрать такое говно предлагаю ввести [формы заполнения проблемы](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository). Так становится и легче читать, и легче заполнять проблему.

**Comment by Zvbhrf** [comment]
Займусь этим через время

**Comment by Zvbhrf** [comment]
Вспомнил и сделал.
